modLoader="javafml"
loaderVersion="${loader_version_range}"
recommendedForge="${forge_version}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}\n"
authors="${mod_authors}"
logoFile="balanced_enchantments.png"
description='''${mod_description}

Any issues just pm me on curseforge or github

https://github.com/ShinJoy991/Balanced-Enchantments

https://www.curseforge.com/minecraft/mc-mods/balanced-enchantments

'''

[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
